/*
 * generated by Xtext
 */
package avroclipse.serializer;

import avroclipse.avroIDL.Annotation;
import avroclipse.avroIDL.Argument;
import avroclipse.avroIDL.Array;
import avroclipse.avroIDL.ArrayFieldType;
import avroclipse.avroIDL.AvroIDLFile;
import avroclipse.avroIDL.AvroIDLPackage;
import avroclipse.avroIDL.BooleanValue;
import avroclipse.avroIDL.CustomTypeLink;
import avroclipse.avroIDL.EnumType;
import avroclipse.avroIDL.ErrorType;
import avroclipse.avroIDL.Field;
import avroclipse.avroIDL.FixedType;
import avroclipse.avroIDL.Import;
import avroclipse.avroIDL.IntValue;
import avroclipse.avroIDL.MapFieldType;
import avroclipse.avroIDL.Null;
import avroclipse.avroIDL.PrimativeTypeLink;
import avroclipse.avroIDL.Protocol;
import avroclipse.avroIDL.RPCMessage;
import avroclipse.avroIDL.RecordType;
import avroclipse.avroIDL.SimpleFieldType;
import avroclipse.avroIDL.StringValue;
import avroclipse.avroIDL.TypeDef;
import avroclipse.avroIDL.UnionFieldType;
import avroclipse.avroIDL.Values;
import avroclipse.avroIDL.VoidTypeLink;
import avroclipse.services.AvroIDLGrammarAccess;
import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class AvroIDLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private AvroIDLGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == AvroIDLPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case AvroIDLPackage.ANNOTATION:
				sequence_Annotation(context, (Annotation) semanticObject); 
				return; 
			case AvroIDLPackage.ARGUMENT:
				sequence_Argument(context, (Argument) semanticObject); 
				return; 
			case AvroIDLPackage.ARRAY:
				sequence_Array(context, (Array) semanticObject); 
				return; 
			case AvroIDLPackage.ARRAY_FIELD_TYPE:
				sequence_ArrayFieldType(context, (ArrayFieldType) semanticObject); 
				return; 
			case AvroIDLPackage.AVRO_IDL_FILE:
				sequence_AvroIDLFile(context, (AvroIDLFile) semanticObject); 
				return; 
			case AvroIDLPackage.BOOLEAN_VALUE:
				sequence_BooleanValue(context, (BooleanValue) semanticObject); 
				return; 
			case AvroIDLPackage.CUSTOM_TYPE_LINK:
				sequence_CustomTypeLink(context, (CustomTypeLink) semanticObject); 
				return; 
			case AvroIDLPackage.ENUM_TYPE:
				sequence_EnumType(context, (EnumType) semanticObject); 
				return; 
			case AvroIDLPackage.ERROR_TYPE:
				sequence_ErrorType(context, (ErrorType) semanticObject); 
				return; 
			case AvroIDLPackage.FIELD:
				sequence_Field(context, (Field) semanticObject); 
				return; 
			case AvroIDLPackage.FIXED_TYPE:
				sequence_FixedType(context, (FixedType) semanticObject); 
				return; 
			case AvroIDLPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case AvroIDLPackage.INT_VALUE:
				sequence_IntValue(context, (IntValue) semanticObject); 
				return; 
			case AvroIDLPackage.MAP_FIELD_TYPE:
				sequence_MapFieldType(context, (MapFieldType) semanticObject); 
				return; 
			case AvroIDLPackage.NULL:
				sequence_Null(context, (Null) semanticObject); 
				return; 
			case AvroIDLPackage.PRIMATIVE_TYPE_LINK:
				sequence_PrimativeTypeLink(context, (PrimativeTypeLink) semanticObject); 
				return; 
			case AvroIDLPackage.PROTOCOL:
				sequence_Protocol(context, (Protocol) semanticObject); 
				return; 
			case AvroIDLPackage.RPC_MESSAGE:
				sequence_RPCMessage(context, (RPCMessage) semanticObject); 
				return; 
			case AvroIDLPackage.RECORD_TYPE:
				sequence_RecordType(context, (RecordType) semanticObject); 
				return; 
			case AvroIDLPackage.SIMPLE_FIELD_TYPE:
				sequence_SimpleFieldType(context, (SimpleFieldType) semanticObject); 
				return; 
			case AvroIDLPackage.STRING_VALUE:
				sequence_StringValue(context, (StringValue) semanticObject); 
				return; 
			case AvroIDLPackage.TYPE_DEF:
				sequence_TypeDef(context, (TypeDef) semanticObject); 
				return; 
			case AvroIDLPackage.UNION_FIELD_TYPE:
				sequence_UnionFieldType(context, (UnionFieldType) semanticObject); 
				return; 
			case AvroIDLPackage.VALUES:
				sequence_Values(context, (Values) semanticObject); 
				return; 
			case AvroIDLPackage.VOID_TYPE_LINK:
				sequence_VoidTypeLink(context, (VoidTypeLink) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (name=AN values=Values?)
	 */
	protected void sequence_Annotation(EObject context, Annotation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (type=TypeLink name=EscapableId default=Value?)
	 */
	protected void sequence_Argument(EObject context, Argument semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (annotation=Annotation? type=TypeLink)
	 */
	protected void sequence_ArrayFieldType(EObject context, ArrayFieldType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     values=Values
	 */
	protected void sequence_Array(EObject context, Array semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.ARRAY__VALUES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.ARRAY__VALUES));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getArrayAccess().getValuesValuesParserRuleCall_1_0(), semanticObject.getValues());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (imports+=Import* protocols+=Protocol?)
	 */
	protected void sequence_AvroIDLFile(EObject context, AvroIDLFile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     val=Boolean
	 */
	protected void sequence_BooleanValue(EObject context, BooleanValue semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.BOOLEAN_VALUE__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.BOOLEAN_VALUE__VAL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getBooleanValueAccess().getValBooleanParserRuleCall_0(), semanticObject.isVal());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     target=[Type|EscapableId]
	 */
	protected void sequence_CustomTypeLink(EObject context, CustomTypeLink semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.CUSTOM_TYPE_LINK__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.CUSTOM_TYPE_LINK__TARGET));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getCustomTypeLinkAccess().getTargetTypeEscapableIdParserRuleCall_0_1(), semanticObject.getTarget());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=EscapableId literals+=ID literals+=ID*)
	 */
	protected void sequence_EnumType(EObject context, EnumType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=EscapableId fields+=Field*)
	 */
	protected void sequence_ErrorType(EObject context, ErrorType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (annotations+=Annotation* type=FieldType nameAnnotations+=Annotation* name=EscapableId default=Value?)
	 */
	protected void sequence_Field(EObject context, Field semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=EscapableId size=INT)
	 */
	protected void sequence_FixedType(EObject context, FixedType semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.TYPE__NAME));
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.FIXED_TYPE__SIZE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.FIXED_TYPE__SIZE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getFixedTypeAccess().getNameEscapableIdParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFixedTypeAccess().getSizeINTTerminalRuleCall_3_0(), semanticObject.getSize());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (type=ImportType importURI=STRING)
	 */
	protected void sequence_Import(EObject context, Import semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.IMPORT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.IMPORT__TYPE));
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.IMPORT__IMPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.IMPORT__IMPORT_URI));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getImportAccess().getTypeImportTypeEnumRuleCall_1_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_2_0(), semanticObject.getImportURI());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (val=INT | val=NegativeInt)
	 */
	protected void sequence_IntValue(EObject context, IntValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (annotation=Annotation? type=TypeLink)
	 */
	protected void sequence_MapFieldType(EObject context, MapFieldType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     val='null'
	 */
	protected void sequence_Null(EObject context, Null semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.NULL__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.NULL__VAL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getNullAccess().getValNullKeyword_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         target='int' | 
	 *         target='long' | 
	 *         target='string' | 
	 *         target='boolean' | 
	 *         target='float' | 
	 *         target='double' | 
	 *         target='null' | 
	 *         target='bytes'
	 *     )
	 */
	protected void sequence_PrimativeTypeLink(EObject context, PrimativeTypeLink semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (annotations+=Annotation* name=EscapableId elements+=Element*)
	 */
	protected void sequence_Protocol(EObject context, Protocol semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (returnType=ReturnTypeLink name=EscapableId (arguments+=Argument arguments+=Argument*)* error=[ErrorType|EscapableId]? oneway?='oneway'?)
	 */
	protected void sequence_RPCMessage(EObject context, RPCMessage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=EscapableId fields+=Field*)
	 */
	protected void sequence_RecordType(EObject context, RecordType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     type=TypeLink
	 */
	protected void sequence_SimpleFieldType(EObject context, SimpleFieldType semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.SIMPLE_FIELD_TYPE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.SIMPLE_FIELD_TYPE__TYPE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getSimpleFieldTypeAccess().getTypeTypeLinkParserRuleCall_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     val=STRING
	 */
	protected void sequence_StringValue(EObject context, StringValue semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.STRING_VALUE__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.STRING_VALUE__VAL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getStringValueAccess().getValSTRINGTerminalRuleCall_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (annotations+=Annotation* type=Type)
	 */
	protected void sequence_TypeDef(EObject context, TypeDef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (types+=TypeLink types+=TypeLink*)
	 */
	protected void sequence_UnionFieldType(EObject context, UnionFieldType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     ((value+=Array | (value+=Value value+=Value*))*)
	 */
	protected void sequence_Values(EObject context, Values semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     target='void'
	 */
	protected void sequence_VoidTypeLink(EObject context, VoidTypeLink semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AvroIDLPackage.Literals.VOID_TYPE_LINK__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AvroIDLPackage.Literals.VOID_TYPE_LINK__TARGET));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getVoidTypeLinkAccess().getTargetVoidKeyword_0(), semanticObject.getTarget());
		feeder.finish();
	}
}
