/*
 * generated by Xtext
 */
package avroclipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AvdlRuntimeModule extends avroclipse.AbstractAvdlRuntimeModule {

}
