/*
 * generated by Xtext
 */
package avroclipse;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AvdlStandaloneSetup extends AvdlStandaloneSetupGenerated{

	public static void doSetup() {
		new AvdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

