/*
 * generated by Xtext
 */
package avroclipse;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AvroIDLStandaloneSetup extends AvroIDLStandaloneSetupGenerated{

	public static void doSetup() {
		new AvroIDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

