/*
 * generated by Xtext
 */
package avroclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AvdlUiModule extends avroclipse.ui.AbstractAvdlUiModule {
	public AvdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
