/*
 * generated by Xtext
 */
package avroclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import avroclipse.ui.highlighting.AvdlHighlightingConfiguration;
import avroclipse.ui.highlighting.AvdlSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AvdlUiModule extends avroclipse.ui.AbstractAvdlUiModule {
	public AvdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return AvdlSemanticHighlightingCalculator.class;
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return AvdlHighlightingConfiguration.class;
	}
}
