/*
 * generated by Xtext
 */
package avroclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import avroclipse.ui.highlighting.AvroIDLAntlrTokenToAttributeIdMapper;
import avroclipse.ui.highlighting.AvroIDLHighlightingConfiguration;
import avroclipse.ui.highlighting.AvroIDLSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AvroIDLUiModule extends avroclipse.ui.AbstractAvroIDLUiModule {
	public AvroIDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return AvroIDLHighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return AvroIDLSemanticHighlightingCalculator.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AvroIDLAntlrTokenToAttributeIdMapper.class;
	}
}
