/*
 * generated by Xtext
 */
package avroclipse.ui.contentassist

import avroclipse.ui.contentassist.AbstractAvdlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AvdlProposalProvider extends AbstractAvdlProposalProvider {
}
