/*
 * generated by Xtext
 */
package avroclipse.ui.contentassist

import avroclipse.ui.contentassist.AbstractAvroIDLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AvroIDLProposalProvider extends AbstractAvroIDLProposalProvider {
}
