/*
 * generated by Xtext
 */
package avroclipse.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import avroclipse.services.AvdlGrammarAccess;

public class AvdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AvdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected avroclipse.parser.antlr.internal.InternalAvdlParser createParser(XtextTokenStream stream) {
		return new avroclipse.parser.antlr.internal.InternalAvdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AvdlFile";
	}
	
	public AvdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AvdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
