/*
 * generated by Xtext
 */
package avroclipse.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import avroclipse.services.AvroIDLGrammarAccess;

public class AvroIDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AvroIDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected avroclipse.parser.antlr.internal.InternalAvroIDLParser createParser(XtextTokenStream stream) {
		return new avroclipse.parser.antlr.internal.InternalAvroIDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AvroIDLFile";
	}
	
	public AvroIDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AvroIDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
