/*
 * generated by Xtext
 */
package avroclipse.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAvdlValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(avroclipse.avdl.AvdlPackage.eINSTANCE);
		return result;
	}
}
