/*
 * generated by Xtext
 */
package avroclipse.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import avroclipse.ui.internal.AvroIDLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AvroIDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AvroIDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AvroIDLActivator.getInstance().getInjector(AvroIDLActivator.AVROCLIPSE_AVROIDL);
	}
	
}
